# Generated by Django 4.2.4 on 2023-08-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, null=True)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('confirm_password', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
                ('id_number', models.IntegerField(unique=True)),
                ('id_picture', models.ImageField(upload_to='id_pics')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_receipts', models.ImageField(upload_to='rent_receipts')),
                ('electricity_receipts', models.ImageField(null=True, upload_to='electricity_receipts/')),
                ('water_receipts', models.ImageField(upload_to='water_receipts')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.customer')),
            ],
        ),
    ]
